config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'registrations/new'

  root 'home#index'
  get 'home', to: 'home#index'

  resources :posts

  resources :users

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, length: { in: 6..200 }

  belongs_to :user
  belongs_to :post
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes

  attribute :user

end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, length: { in: 2..40 }
  validates :body, length: { in: 2..400}

  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, uniqueness: true, length: {minimum: 2}
  validates :password, length: { in: 6..20 }

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end
  def new
    @post = Post.new
    @users = User.all
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to root_path
    else
      flash.now[:alert] = "Something went wrong"
      redirect_to :new_post
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :user_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password,)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to sign_up_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
      @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Welcome Page</h1>

<% if Current.user %>
  <h2>Logged in as:<%= Current.user.username %></h2>
  <%= button_to "Sign Out", logout_path,  method: :delete %>
<% else %>
  <%= link_to "Sign up", sign_up_path %>
  <%= link_to "Sign In", sign_in_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MicroReddit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Posts</h1>
<% @posts.each do |post| %>
  <div class="post">
    <h2><%= post.title %></h2>
    <p><%= post.body %></p>
    <p><%= link_to 'this post', post_path(post) %></p>
    <p>Posted by: <%= post.user.username %></p>
  </div>
<% end %>

<p><%= link_to 'New Post', new_post_path %></p>

app/views/posts/new.html.erb
<!-- app/views/posts/new.html.erb -->
<h1>New Post</h1>

<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br/>

  <%= f.label :body %>
  <%= f.text_area :body %><br/>

  <%= f.label :user_id, "Author" %>
  <%= f.collection_select :user_id, @users, :id, :username, prompt: 'Select author' %><br/>

  <%= f.submit "Create Post" %>
<% end %>

<%= link_to "Back", posts_path %>

app/views/posts/show.html.erb
<h1>Posts</h1>
  <div class="post">
    <h2><%= @post.title %></h2>
    <p><%= @post.body %></p>
    <p>Posted by: <%= @post.user.username %></p>
  </div>

<p><%= link_to 'New Post', new_post_path %></p>
<p><%= link_to 'View all posts', posts_path %></p>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= user.username %>
    </li>
    <li>
      <%= user.password %>
    </li>
    <li>
      <ul>
      <% user.posts.each do |post| %>
      <li>
        <%= post.title %>
      </li>
      <li>
        <%= post.body %>
      </li>
      <% end %>
        </ul>
    </li>
    <li>
      <ul>
        <% user.comments.each do |comment| %>
          <li>
            <%= comment.body %>
          </li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>